INCLUDES= -I ./
OBJECTS= ./build/List.o
LIST= ./build/List.o

all: ${OBJECTS}
		gcc main.c -o main ${OBJECTS} -g

list: ${LIST}
		gcc listTest.c -o listTest ${LIST} -g

./build/List.o: ./List.c
	gcc List.c ${INCLUDES} -o ./build/List.o -g -c


clean:
		rm -rf ${OBJECTS}
		rm -rf main

cleanlist:
		rm -rf ${LIST}
		rm -rf listTest